POST http://localhost:8080/events
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTc1MzIwNjYzNiwidXNlcklkIjoyfQ.dwiISJD8Li9Unkk-7DPZlxPoyFuEcH3gWGM34Llxmus
Accept: application/json

{
    "name": "Test event2",
    "description": "Test description2",
    "location": "Test location",
    "datetime": "2025-007-18T15:30:00.00Z"
}