DELETE http://localhost:8080/events/4
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InRlc3QyQGdtYWlsLmNvbSIsImV4cCI6MTc1MzAzNTE4NSwidXNlcklkIjoyfQ.QiMWL8pmbShmv1ot5hoDv98we9Z3MhoO8dzuKxDR6aY